### ISSUE TITLE
JS Controller 5 tracking 

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.repositories#2514]
**This is a tracking issue only for tracking adapters which need an update for js-controller 5 but are not yet at stable repository.**

# Overview

❗ offen, Fragen zu klären
⌛ in Arbeit, alles geklärt
✅ ok, alles erledigt
🚫 adapter wird mit js-controlle 5 nicht mehr unterstützt
⚪ nicht für js-controller 5 relevant oder Adapter nicht im Repository
:mega: dev kontaktiert, warte auf Feedback

- [x] ✅ [acme](https://github.com/iobroker-community-adapters/ioBroker.acme) - required: none / 0.1.0 - released
- [x] ✅ [admin](https://github.com/iobroker/iobroker.admin) - required: 6.8.0 - released
- [x] ✅ [anelhut](https://github.com/dan1-de/ioBroker.anelhut) - required: 1.0.15 - released
- [x] ✅ [b-control-em](https://github.com/ioBroker/ioBroker.b-control-em) - required: 0.3.1 - released
- [x] ⚪ [bosch-ebike](https://github.com/TA2k/ioBroker.bosch-ebike) - required: none
- [x] ✅ [cul](https://github.com/ioBroker/ioBroker.cul) - required: 2.2.0 - released (no change)
- [x] ✅ [daikin-cloud](https://github.com/Apollon77/ioBroker.daikin-cloud) - required: 0.3.0 - released
- [x] ✅ [doorbird](https://github.com/iobroker-community-adapters/iobroker.doorbird)  - required: 0.1.7 - newer released
- [x] ✅ [ds18b20](https://github.com/crycode-de/ioBroker.ds18b20) - required: 2.0.4 - released
- [x] ✅ [energymanager](https://github.com/unltdnetworx/ioBroker.energymanager) - required: 1.4.2 - released
- [x] ⚪ [enigma2](https://github.com/iobroker-community-adapters/iobroker.enigma2) - required: none - not at stable yet
- [x] ✅ [fakeroku](https://github.com/iobroker-community-adapters/iobroker.fakeroku) - required: 0.2.2+ - released
- [x] ✅ [fhem](https://github.com/iobroker-community-adapters/ioBroker.fhem) - required: 2.0.5 - released
- [x] ✅ [history](https://github.com/iobroker/ioBroker.history) - required: 2.2.6 - released
- [x] ✅ [iqontrol](https://github.com/sbormann/ioBroker.iqontrol) - required: 2.3.0 - released
- [x] ⚪ [javascript](https://github.com/ioBroker/ioBroker.javascript) - required: none
- [x] 🚫 [km200](https://github.com/iobroker-community-adapters/iobroker.km200) - deprecated - Ersatz: ems-esp
- [x] ✅ [lgtv](https://github.com/SebastianSchultz/ioBroker.lgtv) - required: 1.1.12 - released
- [ ] ❗[linux-control](https://github.com/Scrounger/ioBroker.linux-control) - required: ???
- [x] ✅ [maxcul](https://github.com/ioBroker/ioBroker.maxcul) - required: 1.3.1 (no change)
- [x] ⚪ [miio](https://github.com/smarthomefans/ioBroker.miio) - required: none - not at stable  
- [x] ✅ [mydlink](https://github.com/iobroker-community-adapters/ioBroker.mydlink) - required: 1.3.4 - released
- [x] ✅ [nanoleaf-lightpanales](https://github.com/daniel-2k/ioBroker.nanoleaf-lightpanels) - required: 1.4.0 - released
- [x] ✅ [node-red](https://github.com/ioBroker/ioBroker.node-red) - required: 4.03+ (no change)
- [x] ✅ [notification.manager](https://github.com/foxriver76/ioBroker.notification-manager) - required: 0.1.1 - released
- [x] ✅ [pi-hole](https://github.com/unltdnetworx/ioBroker.pi-hole) - required: 1.3.6+ - released
- [x] ✅ [ping](https://github.com/ioBroker/ioBroker.ping) - required: 1.6.2 - released
- [x] ✅ [pushbullet](https://github.com/Jens1809/ioBroker.pushbullet) - required: 1.0.1 - released
- [x] 🚫 [samsung_tyzen](https://github.com/dahuby/iobroker.samsung_tizen) - stale repo - deprecated with js-controller 5
- [x] ✅ [socketio](https://github.com/ioBroker/ioBroker.socketio) - required: 6.5.2 - released 
- [x] ✅ [stiebel-isg](https://github.com/unltdnetworx/ioBroker.stiebel-isg) - required: 1.7.6+ - newer released
- [x] ✅ [systeminfo](https://github.com/iobroker-community-adapters/ioBroker.systeminfo) - required: 1.0.0 - released
- [x] ✅ [viessmann](https://github.com/misanorot/ioBroker.viessmann) - required: 1.4.4+ - released 
- [x] ✅ [web](https://github.com/ioBroker/ioBroker.web) - required: 6.1.0 - released 
- [x] ✅ [ws](https://github.com/ioBroker/ioBroker.ws) - required: 2.5.3 - released 
- [x] ✅[yahka](https://github.com/jensweigele/ioBroker.yahka) - required: 1.0.1 - newer version released
- [x] ✅ [zigbee](https://github.com/ioBroker/ioBroker.zigbee) - required: 1.8.23 - released

**Comment by mcm1957** [comment]
Details:

**anelhut**
**Adapter repo:** https://github.com/dan1-de/ioBroker.anelhut
**stable PR:** https://github.com/ioBroker/ioBroker.repositories/pull/2507
**Problem:** https://github.com/dan1-de/ioBroker.anelhut/issues/35
**Remarks** Not at stable as PR is delayed. github testing not operational

**xxx**
**Adapter repo:**
**stable PR:** 
**Problem:** 
**Remarks**

**Comment by mcm1957** [comment]
-spare-

**Comment by mcm1957** [comment]
**Liste von Forumsbeiträgen die potenzielle Adapterprobleme betreffen.**
(checked bedeutet dass der Fall analysiert ist und der Adapter ggF. in die mianliste eingetragen wurde)


- [ ] Samsung_Tizen - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/515 GH only Adapter
- [ ] fhem - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/476
- [ ] maxcul - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/425
- [ ] nanoleaf-lights - benötigt update - Version 1.4.0 sollte ab morgen im Latest sein. (@rogni) - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/414
- [ ] zigbee - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/408
- [ ] iqontrol - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/407
- [ ] systeminfo - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/376
- [ ] B-Control-EM update nötig https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/369
- [ ] doorbird - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/368
- [ ] javascript ???
- [ ] Daikin cloud https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/353
- [ ] Notification-Managers - ???
- [ ] Node Red - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/282
- [ ] iqontraol, node red - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/278
- [ ] bosch ebike - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/263
- [ ] diverse - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/241
- [ ] web - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/223
- [ ] viessmann - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/208
- [ ] ping - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/145
- [ ] ping - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/118
- [ ] fakeroku - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/98
- [ ] miio - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/102
- [ ] yaahka - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/74
- [ ] lgtv - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/47
- [ ] fhem - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/47
- [ ] cul - https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/14

**Comment by mcm1957** [comment]
- spare -

**Comment by mcm1957** [comment]
- spare -

**Comment by mcm1957** [comment]
Liebe Beta-User und Tester,

Vorab ein ganz herzliches **DANKE** für eure Mühe und die zahlreichen Feedbacks zur Qualitätsverbesserung.  

Da nun der js-controller 5 in sehr naher Zukunft im stable Repository aufgenommen werden soll, versuchen wir sicherzustellen, dass alle Adapter die in den letzten Wochen eine Anpassung erhalten haben auch in einer für den js-controller 5 geeigneten Release im stable Repository verfügbar sind. Ich habe dazu aus den Informationen in diesem Topic eine Liste von Adaptern zusammengestellt, die davon (potenziell) betroffen sind. Diese kommt im nächsten Beitrag.

Bei jedem Adapter ist angegeben, welche Release für js-controller 5 mindestens erforderlich ist und ob diese bereits im stable verfügbar ist. Einige wenige hier angesprochene Adapter werden unter js-controller 5 nicht mehr unterstützt, vor allem da sie nicht mehr gewartet werden. Diese sind entsprechend markiert. Adapter die noch nie im stable repository waren, sind ebenfalls markiert da es hier vom dev abhängt wann er diese für stable ready hält.

**Und nun mein BITTE:**

Falls ihr im Zuge eurer Tests weitere Adapter (die nicht in der nachfolgenden Liste stehen) entdeckt habt die im ioBroker repository gelistet sind gebt diese bitte bekannt und schreibt dazu 

-) ob der Adapter nun mit der aktuellen Release im latest funktioniert
-) ob der Adapter nur via github Installation funktioniert
-) ob der Adapter vom dev gar nicht angepasst wurde und daher nicht mehr funktioniert

Sofern bekannt verlinkt bitte das entsprechende Issue.

Ziel der Aktion ist vor allem sicherzustellen dass verbesserte Adapter auch sicher ins stable Repository kommmen. Zu dem Zweck werde ich den entsprechenden Maintainern ggF nachlaufen und abzuklären versuchen ob noch etwas gegen einen stable Update spricht.

DANKE für eure Unterstützung
mcm1957

**Comment by mcm1957** [comment]
ds18b20 braucht Update
https://forum.iobroker.net/topic/66985/test-adapter-ds18b20-v2-0-x/8

**Comment by mcm1957** [comment]
js-controller 5 has been released.
So lets close here
